name: 02 - Workflow Events

on: 
  push:
    branches:
      - "main"
  pull_request:
    types:
      - "opened"
      - "reopened"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Type of the workflow"