name: 05 - 2 - Event Filters and Activity Types

on:
  pull_request:
    branches:
      - "main"
    types:
      - "closed"

jobs:
  echo-closed-pr:
    runs-on: ubuntu-latest
    steps:
      - name: "Print on close Pull_Request"
        run: echo "Running whenever a PR is closed"