name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

on:
  #push:
  workflow_dispatch:
    inputs:
      debug:
        description: "value"
        type: boolean
        default: false

env:
  my_var_assigment: ${{ vars.MY_VAR || 'default_value'}}
  my_new_assigment: ${{ vars.MY_VAR_new || 'default_value'}}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      
      - name: "[debug] Print when triggered from main"
        if: ${{ inputs.debug  && github.ref == 'refs/heads/main'}}
        run: echo "I was triggered from main"

      - name: Greeting
        run: |
          echo "Hello, world"
          echo "Repo varibale value present - ${{ env.my_var_assigment}}"
          echo "Repo varibale value not present - ${{ env.my_new_assigment}}"
