name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: "Whether to execute cache step"
      node-version:
        type: choice
        options:
          - "18.x"
          - "20.x"
          - "21.x"
        default: "20.x"
        description: "Node version"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      
      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        if: ${{ inputs.use-cache }}
        with:
          path: 13-caching/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}

      - name: cache-status
        run: |
          echo "cache request - ${{ inputs.use-cache }}"
          echo "cache hits - ${{ steps.cache.outputs.cache-hit }}"
      
      - name: Install dependencies
        if: ${{ !steps.cache.outputs.cache-hit}}
        run: npm ci

      - name: Testing
        run: npm run build
      
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"
      
      